# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CountryCode.create(:country => 'Afghanistan', :code_2 => 'AF', :code_3 => 'AFG', :country_ja => 'アフガニスタン', :area => '中東', :code_type => 'ISO 3166-2:AF')
CountryCode.create(:country => 'Åland Islands', :code_2 => 'AX', :code_3 => 'ALA', :country_ja => 'オーランド諸島', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:AX')
CountryCode.create(:country => 'Albania', :code_2 => 'AL', :code_3 => 'ALB', :country_ja => 'アルバニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:AL')
CountryCode.create(:country => 'Algeria', :code_2 => 'DZ', :code_3 => 'DZA', :country_ja => 'アルジェリア', :area => '北アフリカ', :code_type => 'ISO 3166-2:DZ')
CountryCode.create(:country => 'American Samoa', :code_2 => 'AS', :code_3 => 'ASM', :country_ja => 'アメリカ領サモア', :area => 'オセアニア', :code_type => 'ISO 3166-2:AS')
CountryCode.create(:country => 'Andorra', :code_2 => 'AD', :code_3 => 'AND', :country_ja => 'アンドラ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:AD')
CountryCode.create(:country => 'Angola', :code_2 => 'AO', :code_3 => 'AGO', :country_ja => 'アンゴラ', :area => '南アフリカ', :code_type => 'ISO 3166-2:AO')
CountryCode.create(:country => 'Anguilla', :code_2 => 'AI', :code_3 => 'AIA', :country_ja => 'アンギラ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:AI')
CountryCode.create(:country => 'Antarctica', :code_2 => 'AQ', :code_3 => 'ATA', :country_ja => '南極', :area => '南極', :code_type => 'ISO 3166-2:AQ')
CountryCode.create(:country => 'Antigua and Barbuda', :code_2 => 'AG', :code_3 => 'ATG', :country_ja => 'アンティグア・バーブーダ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:AG')
CountryCode.create(:country => 'Argentina', :code_2 => 'AR', :code_3 => 'ARG', :country_ja => 'アルゼンチン', :area => '南アメリカ', :code_type => 'ISO 3166-2:AR')
CountryCode.create(:country => 'Armenia', :code_2 => 'AM', :code_3 => 'ARM', :country_ja => 'アルメニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:AM')
CountryCode.create(:country => 'Aruba', :code_2 => 'AW', :code_3 => 'ABW', :country_ja => 'アルバ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:AW')
CountryCode.create(:country => 'Australia', :code_2 => 'AU', :code_3 => 'AUS', :country_ja => 'オーストラリア', :area => 'オセアニア', :code_type => 'ISO 3166-2:AU')
CountryCode.create(:country => 'Austria', :code_2 => 'AT', :code_3 => 'AUT', :country_ja => 'オーストリア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:AT')
CountryCode.create(:country => 'Azerbaijan', :code_2 => 'AZ', :code_3 => 'AZE', :country_ja => 'アゼルバイジャン', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:AZ')
CountryCode.create(:country => 'Bahamas', :code_2 => 'BS', :code_3 => 'BHS', :country_ja => 'バハマ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BS')
CountryCode.create(:country => 'Bahrain', :code_2 => 'BH', :code_3 => 'BHR', :country_ja => 'バーレーン', :area => '中東', :code_type => 'ISO 3166-2:BH')
CountryCode.create(:country => 'Bangladesh', :code_2 => 'BD', :code_3 => 'BGD', :country_ja => 'バングラデシュ', :area => '南アジア', :code_type => 'ISO 3166-2:BD')
CountryCode.create(:country => 'Barbados', :code_2 => 'BB', :code_3 => 'BRB', :country_ja => 'バルバドス', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BB')
CountryCode.create(:country => 'Belarus', :code_2 => 'BY', :code_3 => 'BLR', :country_ja => 'ベラルーシ', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:BY')
CountryCode.create(:country => 'Belgium', :code_2 => 'BE', :code_3 => 'BEL', :country_ja => 'ベルギー', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:BE')
CountryCode.create(:country => 'Belize', :code_2 => 'BZ', :code_3 => 'BLZ', :country_ja => 'ベリーズ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BZ')
CountryCode.create(:country => 'Benin', :code_2 => 'BJ', :code_3 => 'BEN', :country_ja => 'ベナン', :area => '西アフリカ', :code_type => 'ISO 3166-2:BJ')
CountryCode.create(:country => 'Bermuda', :code_2 => 'BM', :code_3 => 'BMU', :country_ja => 'バミューダ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BM')
CountryCode.create(:country => 'Bhutan', :code_2 => 'BT', :code_3 => 'BTN', :country_ja => 'ブータン', :area => '南アジア', :code_type => 'ISO 3166-2:BT')
CountryCode.create(:country => 'Bolivia, Plurinational State of', :code_2 => 'BO', :code_3 => 'BOL', :country_ja => 'ボリビア多民族国', :area => '南アメリカ', :code_type => 'ISO 3166-2:BO')
CountryCode.create(:country => 'Bonaire, Saint Eustatius and Saba', :code_2 => 'BQ', :code_3 => 'BES', :country_ja => 'ボネール、シント・ユースタティウスおよびサバ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BQ')
CountryCode.create(:country => 'Bosnia and Herzegovina', :code_2 => 'BA', :code_3 => 'BIH', :country_ja => 'ボスニア・ヘルツェゴビナ', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:BA')
CountryCode.create(:country => 'Botswana', :code_2 => 'BW', :code_3 => 'BWA', :country_ja => 'ボツワナ', :area => '南アフリカ', :code_type => 'ISO 3166-2:BW')
CountryCode.create(:country => 'Bouvet Island', :code_2 => 'BV', :code_3 => 'BVT', :country_ja => 'ブーベ島', :area => '南極', :code_type => 'ISO 3166-2:BV')
CountryCode.create(:country => 'Brazil', :code_2 => 'BR', :code_3 => 'BRA', :country_ja => 'ブラジル', :area => '南アメリカ', :code_type => 'ISO 3166-2:BR')
CountryCode.create(:country => 'British Indian Ocean Territory', :code_2 => 'IO', :code_3 => 'IOT', :country_ja => 'イギリス領インド洋地域', :area => 'インド洋地域', :code_type => 'ISO 3166-2:IO')
CountryCode.create(:country => 'Brunei Darussalam', :code_2 => 'BN', :code_3 => 'BRN', :country_ja => 'ブルネイ・ダルサラーム', :area => '東南アジア', :code_type => 'ISO 3166-2:BN')
CountryCode.create(:country => 'Bulgaria', :code_2 => 'BG', :code_3 => 'BGR', :country_ja => 'ブルガリア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:BG')
CountryCode.create(:country => 'Burkina Faso', :code_2 => 'BF', :code_3 => 'BFA', :country_ja => 'ブルキナファソ', :area => '西アフリカ', :code_type => 'ISO 3166-2:BF')
CountryCode.create(:country => 'Burundi', :code_2 => 'BI', :code_3 => 'BDI', :country_ja => 'ブルンジ', :area => '中央アフリカ', :code_type => 'ISO 3166-2:BI')
CountryCode.create(:country => 'Cambodia', :code_2 => 'KH', :code_3 => 'KHM', :country_ja => 'カンボジア', :area => '東南アジア', :code_type => 'ISO 3166-2:KH')
CountryCode.create(:country => 'Cameroon', :code_2 => 'CM', :code_3 => 'CMR', :country_ja => 'カメルーン', :area => '中央アフリカ', :code_type => 'ISO 3166-2:CM')
CountryCode.create(:country => 'Canada', :code_2 => 'CA', :code_3 => 'CAN', :country_ja => 'カナダ', :area => '北アメリカ', :code_type => 'ISO 3166-2:CA')
CountryCode.create(:country => 'Cape Verde', :code_2 => 'CV', :code_3 => 'CPV', :country_ja => 'カーボベルデ', :area => '西アフリカ', :code_type => 'ISO 3166-2:CV')
CountryCode.create(:country => 'Cayman Islands', :code_2 => 'KY', :code_3 => 'CYM', :country_ja => 'ケイマン諸島', :area => '中央アメリカ', :code_type => 'ISO 3166-2:KY')
CountryCode.create(:country => 'Central African Republic', :code_2 => 'CF', :code_3 => 'CAF', :country_ja => '中央アフリカ共和国', :area => '中央アフリカ', :code_type => 'ISO 3166-2:CF')
CountryCode.create(:country => 'Chad', :code_2 => 'TD', :code_3 => 'TCD', :country_ja => 'チャド', :area => '中央アフリカ', :code_type => 'ISO 3166-2:TD')
CountryCode.create(:country => 'Chile', :code_2 => 'CL', :code_3 => 'CHL', :country_ja => 'チリ', :area => '南アメリカ', :code_type => 'ISO 3166-2:CL')
CountryCode.create(:country => 'China', :code_2 => 'CN', :code_3 => 'CHN', :country_ja => '中国', :area => '東アジア', :code_type => 'ISO 3166-2:CN')
CountryCode.create(:country => 'Christmas Island', :code_2 => 'CX', :code_3 => 'CXR', :country_ja => 'クリスマス島', :area => 'オセアニア', :code_type => 'ISO 3166-2:CX')
CountryCode.create(:country => 'Cocos (Keeling) Islands', :code_2 => 'CC', :code_3 => 'CCK', :country_ja => 'ココス（キーリング）諸島', :area => 'インド洋地域', :code_type => 'ISO 3166-2:CC')
CountryCode.create(:country => 'Colombia', :code_2 => 'CO', :code_3 => 'COL', :country_ja => 'コロンビア', :area => '南アメリカ', :code_type => 'ISO 3166-2:CO')
CountryCode.create(:country => 'Comoros', :code_2 => 'KM', :code_3 => 'COM', :country_ja => 'コモロ', :area => 'インド洋地域', :code_type => 'ISO 3166-2:KM')
CountryCode.create(:country => 'Congo', :code_2 => 'CG', :code_3 => 'COG', :country_ja => 'コンゴ共和国', :area => '中央アフリカ', :code_type => 'ISO 3166-2:CG')
CountryCode.create(:country => 'Congo, the Democratic Republic of the', :code_2 => 'CD', :code_3 => 'COD', :country_ja => 'コンゴ民主共和国', :area => '中央アフリカ', :code_type => 'ISO 3166-2:CD')
CountryCode.create(:country => 'Cook Islands', :code_2 => 'CK', :code_3 => 'COK', :country_ja => 'クック諸島', :area => 'オセアニア', :code_type => 'ISO 3166-2:CK')
CountryCode.create(:country => 'Costa Rica', :code_2 => 'CR', :code_3 => 'CRI', :country_ja => 'コスタリカ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:CR')
CountryCode.create(:country => 'Côte d\'Ivoire', :code_2 => 'CI', :code_3 => 'CIV', :country_ja => 'コートジボワール', :area => '西アフリカ', :code_type => 'ISO 3166-2:CI')
CountryCode.create(:country => 'Croatia', :code_2 => 'HR', :code_3 => 'HRV', :country_ja => 'クロアチア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:HR')
CountryCode.create(:country => 'Cuba', :code_2 => 'CU', :code_3 => 'CUB', :country_ja => 'キューバ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:CU')
CountryCode.create(:country => 'Curaçao', :code_2 => 'CW', :code_3 => 'CUW', :country_ja => 'キュラソー', :area => '中央アメリカ', :code_type => 'ISO 3166-2:CW')
CountryCode.create(:country => 'Cyprus', :code_2 => 'CY', :code_3 => 'CYP', :country_ja => 'キプロス', :area => '地中海地域', :code_type => 'ISO 3166-2:CY')
CountryCode.create(:country => 'Czech Republic', :code_2 => 'CZ', :code_3 => 'CZE', :country_ja => 'チェコ', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:CZ')
CountryCode.create(:country => 'Denmark', :code_2 => 'DK', :code_3 => 'DNK', :country_ja => 'デンマーク', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:DK')
CountryCode.create(:country => 'Djibouti', :code_2 => 'DJ', :code_3 => 'DJI', :country_ja => 'ジブチ', :area => '東アフリカ', :code_type => 'ISO 3166-2:DJ')
CountryCode.create(:country => 'Dominica', :code_2 => 'DM', :code_3 => 'DMA', :country_ja => 'ドミニカ国', :area => '中央アメリカ', :code_type => 'ISO 3166-2:DM')
CountryCode.create(:country => 'Dominican Republic', :code_2 => 'DO', :code_3 => 'DOM', :country_ja => 'ドミニカ共和国', :area => '中央アメリカ', :code_type => 'ISO 3166-2:DO')
CountryCode.create(:country => 'Ecuador', :code_2 => 'EC', :code_3 => 'ECU', :country_ja => 'エクアドル', :area => '南アメリカ', :code_type => 'ISO 3166-2:EC')
CountryCode.create(:country => 'Egypt', :code_2 => 'EG', :code_3 => 'EGY', :country_ja => 'エジプト', :area => '北アフリカ', :code_type => 'ISO 3166-2:EG')
CountryCode.create(:country => 'El Salvador', :code_2 => 'SV', :code_3 => 'SLV', :country_ja => 'エルサルバドル', :area => '中央アメリカ', :code_type => 'ISO 3166-2:SV')
CountryCode.create(:country => 'Equatorial Guinea', :code_2 => 'GQ', :code_3 => 'GNQ', :country_ja => '赤道ギニア', :area => '中央アフリカ', :code_type => 'ISO 3166-2:GQ')
CountryCode.create(:country => 'Eritrea', :code_2 => 'ER', :code_3 => 'ERI', :country_ja => 'エリトリア', :area => '東アフリカ', :code_type => 'ISO 3166-2:ER')
CountryCode.create(:country => 'Estonia', :code_2 => 'EE', :code_3 => 'EST', :country_ja => 'エストニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:EE')
CountryCode.create(:country => 'Ethiopia', :code_2 => 'ET', :code_3 => 'ETH', :country_ja => 'エチオピア', :area => '東アフリカ', :code_type => 'ISO 3166-2:ET')
CountryCode.create(:country => 'Falkland Islands (Malvinas)', :code_2 => 'FK', :code_3 => 'FLK', :country_ja => 'フォークランド（マルビナス）諸島', :area => '南アメリカ', :code_type => 'ISO 3166-2:FK')
CountryCode.create(:country => 'Faroe Islands', :code_2 => 'FO', :code_3 => 'FRO', :country_ja => 'フェロー諸島', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:FO')
CountryCode.create(:country => 'Fiji', :code_2 => 'FJ', :code_3 => 'FJI', :country_ja => 'フィジー', :area => 'オセアニア', :code_type => 'ISO 3166-2:FJ')
CountryCode.create(:country => 'Finland', :code_2 => 'FI', :code_3 => 'FIN', :country_ja => 'フィンランド', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:FI')
CountryCode.create(:country => 'France', :code_2 => 'FR', :code_3 => 'FRA', :country_ja => 'フランス', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:FR')
CountryCode.create(:country => 'French Guiana', :code_2 => 'GF', :code_3 => 'GUF', :country_ja => 'フランス領ギアナ', :area => '南アメリカ', :code_type => 'ISO 3166-2:GF')
CountryCode.create(:country => 'French Polynesia', :code_2 => 'PF', :code_3 => 'PYF', :country_ja => 'フランス領ポリネシア', :area => 'オセアニア', :code_type => 'ISO 3166-2:PF')
CountryCode.create(:country => 'French Southern Territories', :code_2 => 'TF', :code_3 => 'ATF', :country_ja => 'フランス領南方・南極地域', :area => 'インド洋地域', :code_type => 'ISO 3166-2:TF')
CountryCode.create(:country => 'Gabon', :code_2 => 'GA', :code_3 => 'GAB', :country_ja => 'ガボン', :area => '中央アフリカ', :code_type => 'ISO 3166-2:GA')
CountryCode.create(:country => 'Gambia', :code_2 => 'GM', :code_3 => 'GMB', :country_ja => 'ガンビア', :area => '西アフリカ', :code_type => 'ISO 3166-2:GM')
CountryCode.create(:country => 'Georgia', :code_2 => 'GE', :code_3 => 'GEO', :country_ja => 'グルジア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:GE')
CountryCode.create(:country => 'Germany', :code_2 => 'DE', :code_3 => 'DEU', :country_ja => 'ドイツ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:DE')
CountryCode.create(:country => 'Ghana', :code_2 => 'GH', :code_3 => 'GHA', :country_ja => 'ガーナ', :area => '西アフリカ', :code_type => 'ISO 3166-2:GH')
CountryCode.create(:country => 'Gibraltar', :code_2 => 'GI', :code_3 => 'GIB', :country_ja => 'ジブラルタル', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:GI')
CountryCode.create(:country => 'Greece', :code_2 => 'GR', :code_3 => 'GRC', :country_ja => 'ギリシャ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:GR')
CountryCode.create(:country => 'Greenland', :code_2 => 'GL', :code_3 => 'GRL', :country_ja => 'グリーンランド', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:GL')
CountryCode.create(:country => 'Grenada', :code_2 => 'GD', :code_3 => 'GRD', :country_ja => 'グレナダ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:GD')
CountryCode.create(:country => 'Guadeloupe', :code_2 => 'GP', :code_3 => 'GLP', :country_ja => 'グアドループ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:GP')
CountryCode.create(:country => 'Guam', :code_2 => 'GU', :code_3 => 'GUM', :country_ja => 'グアム', :area => 'オセアニア', :code_type => 'ISO 3166-2:GU')
CountryCode.create(:country => 'Guatemala', :code_2 => 'GT', :code_3 => 'GTM', :country_ja => 'グアテマラ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:GT')
CountryCode.create(:country => 'Guernsey', :code_2 => 'GG', :code_3 => 'GGY', :country_ja => 'ガーンジー', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:GG')
CountryCode.create(:country => 'Guinea', :code_2 => 'GN', :code_3 => 'GIN', :country_ja => 'ギニア', :area => '西アフリカ', :code_type => 'ISO 3166-2:GN')
CountryCode.create(:country => 'Guinea-Bissau', :code_2 => 'GW', :code_3 => 'GNB', :country_ja => 'ギニアビサウ', :area => '西アフリカ', :code_type => 'ISO 3166-2:GW')
CountryCode.create(:country => 'Guyana', :code_2 => 'GY', :code_3 => 'GUY', :country_ja => 'ガイアナ', :area => '南アメリカ', :code_type => 'ISO 3166-2:GY')
CountryCode.create(:country => 'Haiti', :code_2 => 'HT', :code_3 => 'HTI', :country_ja => 'ハイチ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:HT')
CountryCode.create(:country => 'Heard Island and McDonald Islands', :code_2 => 'HM', :code_3 => 'HMD', :country_ja => 'ハード島とマクドナルド諸島', :area => 'インド洋地域', :code_type => 'ISO 3166-2:HM')
CountryCode.create(:country => 'Holy See (Vatican City State)', :code_2 => 'VA', :code_3 => 'VAT', :country_ja => 'バチカン市国', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:VA')
CountryCode.create(:country => 'Honduras', :code_2 => 'HN', :code_3 => 'HND', :country_ja => 'ホンジュラス', :area => '中央アメリカ', :code_type => 'ISO 3166-2:HN')
CountryCode.create(:country => 'Hong Kong', :code_2 => 'HK', :code_3 => 'HKG', :country_ja => '香港', :area => '東アジア', :code_type => 'ISO 3166-2:HK')
CountryCode.create(:country => 'Hungary', :code_2 => 'HU', :code_3 => 'HUN', :country_ja => 'ハンガリー', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:HU')
CountryCode.create(:country => 'Iceland', :code_2 => 'IS', :code_3 => 'ISL', :country_ja => 'アイスランド', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:IS')
CountryCode.create(:country => 'India', :code_2 => 'IN', :code_3 => 'IND', :country_ja => 'インド', :area => '南アジア', :code_type => 'ISO 3166-2:IN')
CountryCode.create(:country => 'Indonesia', :code_2 => 'ID', :code_3 => 'IDN', :country_ja => 'インドネシア', :area => '東南アジア', :code_type => 'ISO 3166-2:ID')
CountryCode.create(:country => 'Iran, Islamic Republic of', :code_2 => 'IR', :code_3 => 'IRN', :country_ja => 'イラン・イスラム共和国', :area => '中東', :code_type => 'ISO 3166-2:IR')
CountryCode.create(:country => 'Iraq', :code_2 => 'IQ', :code_3 => 'IRQ', :country_ja => 'イラク', :area => '中東', :code_type => 'ISO 3166-2:IQ')
CountryCode.create(:country => 'Ireland', :code_2 => 'IE', :code_3 => 'IRL', :country_ja => 'アイルランド', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:IE')
CountryCode.create(:country => 'Isle of Man', :code_2 => 'IM', :code_3 => 'IMN', :country_ja => 'マン島', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:IM')
CountryCode.create(:country => 'Israel', :code_2 => 'IL', :code_3 => 'ISR', :country_ja => 'イスラエル', :area => '中東', :code_type => 'ISO 3166-2:IL')
CountryCode.create(:country => 'Italy', :code_2 => 'IT', :code_3 => 'ITA', :country_ja => 'イタリア', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:IT')
CountryCode.create(:country => 'Jamaica', :code_2 => 'JM', :code_3 => 'JAM', :country_ja => 'ジャマイカ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:JM')
CountryCode.create(:country => 'Japan', :code_2 => 'JP', :code_3 => 'JPN', :country_ja => '日本', :area => '東アジア', :code_type => 'ISO 3166-2:JP')
CountryCode.create(:country => 'Jersey', :code_2 => 'JE', :code_3 => 'JEY', :country_ja => 'ジャージー', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:JE')
CountryCode.create(:country => 'Jordan', :code_2 => 'JO', :code_3 => 'JOR', :country_ja => 'ヨルダン', :area => '中東', :code_type => 'ISO 3166-2:JO')
CountryCode.create(:country => 'Kazakhstan', :code_2 => 'KZ', :code_3 => 'KAZ', :country_ja => 'カザフスタン', :area => '中央アジア', :code_type => 'ISO 3166-2:KZ')
CountryCode.create(:country => 'Kenya', :code_2 => 'KE', :code_3 => 'KEN', :country_ja => 'ケニア', :area => '東アフリカ', :code_type => 'ISO 3166-2:KE')
CountryCode.create(:country => 'Kiribati', :code_2 => 'KI', :code_3 => 'KIR', :country_ja => 'キリバス', :area => 'オセアニア', :code_type => 'ISO 3166-2:KI')
CountryCode.create(:country => 'Korea, Democratic People\'s Republic of', :code_2 => 'KP', :code_3 => 'PRK', :country_ja => '朝鮮民主主義人民共和国', :area => '東アジア', :code_type => 'ISO 3166-2:KP')
CountryCode.create(:country => 'Korea, Republic of', :code_2 => 'KR', :code_3 => 'KOR', :country_ja => '大韓民国', :area => '東アジア', :code_type => 'ISO 3166-2:KR')
CountryCode.create(:country => 'Kuwait', :code_2 => 'KW', :code_3 => 'KWT', :country_ja => 'クウェート', :area => '中東', :code_type => 'ISO 3166-2:KW')
CountryCode.create(:country => 'Kyrgyzstan', :code_2 => 'KG', :code_3 => 'KGZ', :country_ja => 'キルギス', :area => '中央アジア', :code_type => 'ISO 3166-2:KG')
CountryCode.create(:country => 'Lao People\'s Democratic Republic', :code_2 => 'LA', :code_3 => 'LAO', :country_ja => 'ラオス人民民主共和国', :area => '東南アジア', :code_type => 'ISO 3166-2:LA')
CountryCode.create(:country => 'Latvia', :code_2 => 'LV', :code_3 => 'LVA', :country_ja => 'ラトビア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:LV')
CountryCode.create(:country => 'Lebanon', :code_2 => 'LB', :code_3 => 'LBN', :country_ja => 'レバノン', :area => '中東', :code_type => 'ISO 3166-2:LB')
CountryCode.create(:country => 'Lesotho', :code_2 => 'LS', :code_3 => 'LSO', :country_ja => 'レソト', :area => '南アフリカ', :code_type => 'ISO 3166-2:LS')
CountryCode.create(:country => 'Liberia', :code_2 => 'LR', :code_3 => 'LBR', :country_ja => 'リベリア', :area => '西アフリカ', :code_type => 'ISO 3166-2:LR')
CountryCode.create(:country => 'Libya', :code_2 => 'LY', :code_3 => 'LBY', :country_ja => 'リビア', :area => '北アフリカ', :code_type => 'ISO 3166-2:LY')
CountryCode.create(:country => 'Liechtenstein', :code_2 => 'LI', :code_3 => 'LIE', :country_ja => 'リヒテンシュタイン', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:LI')
CountryCode.create(:country => 'Lithuania', :code_2 => 'LT', :code_3 => 'LTU', :country_ja => 'リトアニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:LT')
CountryCode.create(:country => 'Luxembourg', :code_2 => 'LU', :code_3 => 'LUX', :country_ja => 'ルクセンブルク', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:LU')
CountryCode.create(:country => 'Macao', :code_2 => 'MO', :code_3 => 'MAC', :country_ja => 'マカオ', :area => '東アジア', :code_type => 'ISO 3166-2:MO')
CountryCode.create(:country => 'Macedonia, the former Yugoslav Republic of', :code_2 => 'MK', :code_3 => 'MKD', :country_ja => 'マケドニア旧ユーゴスラビア共和国', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:MK')
CountryCode.create(:country => 'Madagascar', :code_2 => 'MG', :code_3 => 'MDG', :country_ja => 'マダガスカル', :area => 'インド洋地域', :code_type => 'ISO 3166-2:MG')
CountryCode.create(:country => 'Malawi', :code_2 => 'MW', :code_3 => 'MWI', :country_ja => 'マラウイ', :area => '南アフリカ', :code_type => 'ISO 3166-2:MW')
CountryCode.create(:country => 'Malaysia', :code_2 => 'MY', :code_3 => 'MYS', :country_ja => 'マレーシア', :area => '東南アジア', :code_type => 'ISO 3166-2:MY')
CountryCode.create(:country => 'Maldives', :code_2 => 'MV', :code_3 => 'MDV', :country_ja => 'モルディブ', :area => 'インド洋地域', :code_type => 'ISO 3166-2:MV')
CountryCode.create(:country => 'Mali', :code_2 => 'ML', :code_3 => 'MLI', :country_ja => 'マリ', :area => '西アフリカ', :code_type => 'ISO 3166-2:ML')
CountryCode.create(:country => 'Malta', :code_2 => 'MT', :code_3 => 'MLT', :country_ja => 'マルタ', :area => '地中海地域', :code_type => 'ISO 3166-2:MT')
CountryCode.create(:country => 'Marshall Islands', :code_2 => 'MH', :code_3 => 'MHL', :country_ja => 'マーシャル諸島', :area => 'オセアニア', :code_type => 'ISO 3166-2:MH')
CountryCode.create(:country => 'Martinique', :code_2 => 'MQ', :code_3 => 'MTQ', :country_ja => 'マルティニーク', :area => '中央アメリカ', :code_type => 'ISO 3166-2:MQ')
CountryCode.create(:country => 'Mauritania', :code_2 => 'MR', :code_3 => 'MRT', :country_ja => 'モーリタニア', :area => '西アフリカ', :code_type => 'ISO 3166-2:MR')
CountryCode.create(:country => 'Mauritius', :code_2 => 'MU', :code_3 => 'MUS', :country_ja => 'モーリシャス', :area => '南アフリカ', :code_type => 'ISO 3166-2:MU')
CountryCode.create(:country => 'Mayotte', :code_2 => 'YT', :code_3 => 'MYT', :country_ja => 'マヨット', :area => 'インド洋地域', :code_type => 'ISO 3166-2:YT')
CountryCode.create(:country => 'Mexico', :code_2 => 'MX', :code_3 => 'MEX', :country_ja => 'メキシコ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:MX')
CountryCode.create(:country => 'Micronesia, Federated States of', :code_2 => 'FM', :code_3 => 'FSM', :country_ja => 'ミクロネシア連邦', :area => 'オセアニア', :code_type => 'ISO 3166-2:FM')
CountryCode.create(:country => 'Moldova, Republic of', :code_2 => 'MD', :code_3 => 'MDA', :country_ja => 'モルドバ共和国', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:MD')
CountryCode.create(:country => 'Monaco', :code_2 => 'MC', :code_3 => 'MCO', :country_ja => 'モナコ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:MC')
CountryCode.create(:country => 'Mongolia', :code_2 => 'MN', :code_3 => 'MNG', :country_ja => 'モンゴル', :area => '東アジア', :code_type => 'ISO 3166-2:MN')
CountryCode.create(:country => 'Montenegro', :code_2 => 'ME', :code_3 => 'MNE', :country_ja => 'モンテネグロ', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:ME')
CountryCode.create(:country => 'Montserrat', :code_2 => 'MS', :code_3 => 'MSR', :country_ja => 'モントセラト', :area => '中央アメリカ', :code_type => 'ISO 3166-2:MS')
CountryCode.create(:country => 'Morocco', :code_2 => 'MA', :code_3 => 'MAR', :country_ja => 'モロッコ', :area => '北アフリカ', :code_type => 'ISO 3166-2:MA')
CountryCode.create(:country => 'Mozambique', :code_2 => 'MZ', :code_3 => 'MOZ', :country_ja => 'モザンビーク', :area => '南アフリカ', :code_type => 'ISO 3166-2:MZ')
CountryCode.create(:country => 'Myanmar', :code_2 => 'MM', :code_3 => 'MMR', :country_ja => 'ミャンマー', :area => '東南アジア', :code_type => 'ISO 3166-2:MM')
CountryCode.create(:country => 'Namibia', :code_2 => 'NA', :code_3 => 'NAM', :country_ja => 'ナミビア', :area => '南アフリカ', :code_type => 'ISO 3166-2:NA')
CountryCode.create(:country => 'Nauru', :code_2 => 'NR', :code_3 => 'NRU', :country_ja => 'ナウル', :area => 'オセアニア', :code_type => 'ISO 3166-2:NR')
CountryCode.create(:country => 'Nepal', :code_2 => 'NP', :code_3 => 'NPL', :country_ja => 'ネパール', :area => '南アジア', :code_type => 'ISO 3166-2:NP')
CountryCode.create(:country => 'Netherlands', :code_2 => 'NL', :code_3 => 'NLD', :country_ja => 'オランダ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:NL')
CountryCode.create(:country => 'New Caledonia', :code_2 => 'NC', :code_3 => 'NCL', :country_ja => 'ニューカレドニア', :area => 'オセアニア', :code_type => 'ISO 3166-2:NC')
CountryCode.create(:country => 'New Zealand', :code_2 => 'NZ', :code_3 => 'NZL', :country_ja => 'ニュージーランド', :area => 'オセアニア', :code_type => 'ISO 3166-2:NZ')
CountryCode.create(:country => 'Nicaragua', :code_2 => 'NI', :code_3 => 'NIC', :country_ja => 'ニカラグア', :area => '中央アメリカ', :code_type => 'ISO 3166-2:NI')
CountryCode.create(:country => 'Niger', :code_2 => 'NE', :code_3 => 'NER', :country_ja => 'ニジェール', :area => '中央アフリカ', :code_type => 'ISO 3166-2:NE')
CountryCode.create(:country => 'Nigeria', :code_2 => 'NG', :code_3 => 'NGA', :country_ja => 'ナイジェリア', :area => '中央アフリカ', :code_type => 'ISO 3166-2:NG')
CountryCode.create(:country => 'Niue', :code_2 => 'NU', :code_3 => 'NIU', :country_ja => 'ニウエ', :area => 'オセアニア', :code_type => 'ISO 3166-2:NU')
CountryCode.create(:country => 'Norfolk Island', :code_2 => 'NF', :code_3 => 'NFK', :country_ja => 'ノーフォーク島', :area => 'オセアニア', :code_type => 'ISO 3166-2:NF')
CountryCode.create(:country => 'Northern Mariana Islands', :code_2 => 'MP', :code_3 => 'MNP', :country_ja => '北マリアナ諸島', :area => 'オセアニア', :code_type => 'ISO 3166-2:MP')
CountryCode.create(:country => 'Norway', :code_2 => 'NO', :code_3 => 'NOR', :country_ja => 'ノルウェー', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:NO')
CountryCode.create(:country => 'Oman', :code_2 => 'OM', :code_3 => 'OMN', :country_ja => 'オマーン', :area => '中東', :code_type => 'ISO 3166-2:OM')
CountryCode.create(:country => 'Pakistan', :code_2 => 'PK', :code_3 => 'PAK', :country_ja => 'パキスタン', :area => '南アジア', :code_type => 'ISO 3166-2:PK')
CountryCode.create(:country => 'Palau', :code_2 => 'PW', :code_3 => 'PLW', :country_ja => 'パラオ', :area => 'オセアニア', :code_type => 'ISO 3166-2:PW')
CountryCode.create(:country => 'Palestinian Territory, Occupied', :code_2 => 'PS', :code_3 => 'PSE', :country_ja => 'パレスチナ', :area => '中東', :code_type => 'ISO 3166-2:PS')
CountryCode.create(:country => 'Panama', :code_2 => 'PA', :code_3 => 'PAN', :country_ja => 'パナマ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:PA')
CountryCode.create(:country => 'Papua New Guinea', :code_2 => 'PG', :code_3 => 'PNG', :country_ja => 'パプアニューギニア', :area => 'オセアニア', :code_type => 'ISO 3166-2:PG')
CountryCode.create(:country => 'Paraguay', :code_2 => 'PY', :code_3 => 'PRY', :country_ja => 'パラグアイ', :area => '南アメリカ', :code_type => 'ISO 3166-2:PY')
CountryCode.create(:country => 'Peru', :code_2 => 'PE', :code_3 => 'PER', :country_ja => 'ペルー', :area => '南アメリカ', :code_type => 'ISO 3166-2:PE')
CountryCode.create(:country => 'Philippines', :code_2 => 'PH', :code_3 => 'PHL', :country_ja => 'フィリピン', :area => '東南アジア', :code_type => 'ISO 3166-2:PH')
CountryCode.create(:country => 'Pitcairn', :code_2 => 'PN', :code_3 => 'PCN', :country_ja => 'ピトケアン', :area => 'オセアニア', :code_type => 'ISO 3166-2:PN')
CountryCode.create(:country => 'Poland', :code_2 => 'PL', :code_3 => 'POL', :country_ja => 'ポーランド', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:PL')
CountryCode.create(:country => 'Portugal', :code_2 => 'PT', :code_3 => 'PRT', :country_ja => 'ポルトガル', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:PT')
CountryCode.create(:country => 'Puerto Rico', :code_2 => 'PR', :code_3 => 'PRI', :country_ja => 'プエルトリコ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:PR')
CountryCode.create(:country => 'Qatar', :code_2 => 'QA', :code_3 => 'QAT', :country_ja => 'カタール', :area => '中東', :code_type => 'ISO 3166-2:QA')
CountryCode.create(:country => 'Réunion', :code_2 => 'RE', :code_3 => 'REU', :country_ja => 'レユニオン', :area => 'インド洋地域', :code_type => 'ISO 3166-2:RE')
CountryCode.create(:country => 'Romania', :code_2 => 'RO', :code_3 => 'ROU', :country_ja => 'ルーマニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:RO')
CountryCode.create(:country => 'Russian Federation', :code_2 => 'RU', :code_3 => 'RUS', :country_ja => 'ロシア連邦', :area => 'ロシア', :code_type => 'ISO 3166-2:RU')
CountryCode.create(:country => 'Rwanda', :code_2 => 'RW', :code_3 => 'RWA', :country_ja => 'ルワンダ', :area => '中央アフリカ', :code_type => 'ISO 3166-2:RW')
CountryCode.create(:country => 'Saint Barthélemy', :code_2 => 'BL', :code_3 => 'BLM', :country_ja => 'サン・バルテルミー', :area => '中央アメリカ', :code_type => 'ISO 3166-2:BL')
CountryCode.create(:country => 'Saint Helena, Ascension and Tristan da Cunha', :code_2 => 'SH', :code_3 => 'SHN', :country_ja => 'セントヘレナ・アセンションおよびトリスタンダクーニャ', :area => '西アフリカ', :code_type => 'ISO 3166-2:SH')
CountryCode.create(:country => 'Saint Kitts and Nevis', :code_2 => 'KN', :code_3 => 'KNA', :country_ja => 'セントクリストファー・ネイビス', :area => '中央アメリカ', :code_type => 'ISO 3166-2:KN')
CountryCode.create(:country => 'Saint Lucia', :code_2 => 'LC', :code_3 => 'LCA', :country_ja => 'セントルシア', :area => '中央アメリカ', :code_type => 'ISO 3166-2:LC')
CountryCode.create(:country => 'Saint Martin (French part)', :code_2 => 'MF', :code_3 => 'MAF', :country_ja => 'サン・マルタン（フランス領）', :area => '中央アメリカ', :code_type => 'ISO 3166-2:MF')
CountryCode.create(:country => 'Saint Pierre and Miquelon', :code_2 => 'PM', :code_3 => 'SPM', :country_ja => 'サンピエール島・ミクロン島', :area => '北アメリカ', :code_type => 'ISO 3166-2:PM')
CountryCode.create(:country => 'Saint Vincent and the Grenadines', :code_2 => 'VC', :code_3 => 'VCT', :country_ja => 'セントビンセントおよびグレナディーン諸島', :area => '中央アメリカ', :code_type => 'ISO 3166-2:VC')
CountryCode.create(:country => 'Samoa', :code_2 => 'WS', :code_3 => 'WSM', :country_ja => 'サモア', :area => 'オセアニア', :code_type => 'ISO 3166-2:WS')
CountryCode.create(:country => 'San Marino', :code_2 => 'SM', :code_3 => 'SMR', :country_ja => 'サンマリノ', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:SM')
CountryCode.create(:country => 'Sao Tome and Principe', :code_2 => 'ST', :code_3 => 'STP', :country_ja => 'サントメ・プリンシペ', :area => '中央アフリカ', :code_type => 'ISO 3166-2:ST')
CountryCode.create(:country => 'Saudi Arabia', :code_2 => 'SA', :code_3 => 'SAU', :country_ja => 'サウジアラビア', :area => '中東', :code_type => 'ISO 3166-2:SA')
CountryCode.create(:country => 'Senegal', :code_2 => 'SN', :code_3 => 'SEN', :country_ja => 'セネガル', :area => '西アフリカ', :code_type => 'ISO 3166-2:SN')
CountryCode.create(:country => 'Serbia', :code_2 => 'RS', :code_3 => 'SRB', :country_ja => 'セルビア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:RS')
CountryCode.create(:country => 'Seychelles', :code_2 => 'SC', :code_3 => 'SYC', :country_ja => 'セーシェル', :area => 'インド洋地域', :code_type => 'ISO 3166-2:SC')
CountryCode.create(:country => 'Sierra Leone', :code_2 => 'SL', :code_3 => 'SLE', :country_ja => 'シエラレオネ', :area => '西アフリカ', :code_type => 'ISO 3166-2:SL')
CountryCode.create(:country => 'Singapore', :code_2 => 'SG', :code_3 => 'SGP', :country_ja => 'シンガポール', :area => '東南アジア', :code_type => 'ISO 3166-2:SG')
CountryCode.create(:country => 'Sint Maarten (Dutch part)', :code_2 => 'SX', :code_3 => 'SXM', :country_ja => 'シント・マールテン（オランダ領）', :area => '中央アメリカ', :code_type => 'ISO 3166-2:SX')
CountryCode.create(:country => 'Slovakia', :code_2 => 'SK', :code_3 => 'SVK', :country_ja => 'スロバキア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:SK')
CountryCode.create(:country => 'Slovenia', :code_2 => 'SI', :code_3 => 'SVN', :country_ja => 'スロベニア', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:SI')
CountryCode.create(:country => 'Solomon Islands', :code_2 => 'SB', :code_3 => 'SLB', :country_ja => 'ソロモン諸島', :area => 'オセアニア', :code_type => 'ISO 3166-2:SB')
CountryCode.create(:country => 'Somalia', :code_2 => 'SO', :code_3 => 'SOM', :country_ja => 'ソマリア', :area => '東アフリカ', :code_type => 'ISO 3166-2:SO')
CountryCode.create(:country => 'South Africa', :code_2 => 'ZA', :code_3 => 'ZAF', :country_ja => '南アフリカ', :area => '南アフリカ', :code_type => 'ISO 3166-2:ZA')
CountryCode.create(:country => 'South Georgia and the South Sandwich Islands', :code_2 => 'GS', :code_3 => 'SGS', :country_ja => 'サウスジョージア・サウスサンドウィッチ諸島', :area => '南アメリカ', :code_type => 'ISO 3166-2:GS')
CountryCode.create(:country => 'South Sudan', :code_2 => 'SS', :code_3 => 'SSD', :country_ja => '南スーダン', :area => '東アフリカ', :code_type => 'ISO 3166-2:SS')
CountryCode.create(:country => 'Spain', :code_2 => 'ES', :code_3 => 'ESP', :country_ja => 'スペイン', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:ES')
CountryCode.create(:country => 'Sri Lanka', :code_2 => 'LK', :code_3 => 'LKA', :country_ja => 'スリランカ', :area => '南アジア', :code_type => 'ISO 3166-2:LK')
CountryCode.create(:country => 'Sudan', :code_2 => 'SD', :code_3 => 'SDN', :country_ja => 'スーダン', :area => '東アフリカ', :code_type => 'ISO 3166-2:SD')
CountryCode.create(:country => 'Suriname', :code_2 => 'SR', :code_3 => 'SUR', :country_ja => 'スリナム', :area => '南アメリカ', :code_type => 'ISO 3166-2:SR')
CountryCode.create(:country => 'Svalbard and Jan Mayen', :code_2 => 'SJ', :code_3 => 'SJM', :country_ja => 'スヴァールバル諸島およびヤンマイエン島', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:SJ')
CountryCode.create(:country => 'Swaziland', :code_2 => 'SZ', :code_3 => 'SWZ', :country_ja => 'スワジランド', :area => '南アフリカ', :code_type => 'ISO 3166-2:SZ')
CountryCode.create(:country => 'Sweden', :code_2 => 'SE', :code_3 => 'SWE', :country_ja => 'スウェーデン', :area => '北ヨーロッパ', :code_type => 'ISO 3166-2:SE')
CountryCode.create(:country => 'Switzerland', :code_2 => 'CH', :code_3 => 'CHE', :country_ja => 'スイス', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:CH')
CountryCode.create(:country => 'Syrian Arab Republic', :code_2 => 'SY', :code_3 => 'SYR', :country_ja => 'シリア・アラブ共和国', :area => '中東', :code_type => 'ISO 3166-2:SY')
CountryCode.create(:country => 'Taiwan, Province of China', :code_2 => 'TW', :code_3 => 'TWN', :country_ja => '台湾（台湾省/中華民国）', :area => '東アジア', :code_type => 'ISO 3166-2:TW')
CountryCode.create(:country => 'Tajikistan', :code_2 => 'TJ', :code_3 => 'TJK', :country_ja => 'タジキスタン', :area => '中央アジア', :code_type => 'ISO 3166-2:TJ')
CountryCode.create(:country => 'Tanzania, United Republic of', :code_2 => 'TZ', :code_3 => 'TZA', :country_ja => 'タンザニア', :area => '東アフリカ', :code_type => 'ISO 3166-2:TZ')
CountryCode.create(:country => 'Thailand', :code_2 => 'TH', :code_3 => 'THA', :country_ja => 'タイ', :area => '東南アジア', :code_type => 'ISO 3166-2:TH')
CountryCode.create(:country => 'Timor-Leste', :code_2 => 'TL', :code_3 => 'TLS', :country_ja => '東ティモール', :area => '東南アジア', :code_type => 'ISO 3166-2:TL')
CountryCode.create(:country => 'Togo', :code_2 => 'TG', :code_3 => 'TGO', :country_ja => 'トーゴ', :area => '西アフリカ', :code_type => 'ISO 3166-2:TG')
CountryCode.create(:country => 'Tokelau', :code_2 => 'TK', :code_3 => 'TKL', :country_ja => 'トケラウ', :area => 'オセアニア', :code_type => 'ISO 3166-2:TK')
CountryCode.create(:country => 'Tonga', :code_2 => 'TO', :code_3 => 'TON', :country_ja => 'トンガ', :area => 'オセアニア', :code_type => 'ISO 3166-2:TO')
CountryCode.create(:country => 'Trinidad and Tobago', :code_2 => 'TT', :code_3 => 'TTO', :country_ja => 'トリニダード・トバゴ', :area => '中央アメリカ', :code_type => 'ISO 3166-2:TT')
CountryCode.create(:country => 'Tunisia', :code_2 => 'TN', :code_3 => 'TUN', :country_ja => 'チュニジア', :area => '北アフリカ', :code_type => 'ISO 3166-2:TN')
CountryCode.create(:country => 'Turkey', :code_2 => 'TR', :code_3 => 'TUR', :country_ja => 'トルコ', :area => '中東', :code_type => 'ISO 3166-2:TR')
CountryCode.create(:country => 'Turkmenistan', :code_2 => 'TM', :code_3 => 'TKM', :country_ja => 'トルクメニスタン', :area => '中央アジア', :code_type => 'ISO 3166-2:TM')
CountryCode.create(:country => 'Turks and Caicos Islands', :code_2 => 'TC', :code_3 => 'TCA', :country_ja => 'タークス・カイコス諸島', :area => '中央アメリカ', :code_type => 'ISO 3166-2:TC')
CountryCode.create(:country => 'Tuvalu', :code_2 => 'TV', :code_3 => 'TUV', :country_ja => 'ツバル', :area => 'オセアニア', :code_type => 'ISO 3166-2:TV')
CountryCode.create(:country => 'Uganda', :code_2 => 'UG', :code_3 => 'UGA', :country_ja => 'ウガンダ', :area => '中央アフリカ', :code_type => 'ISO 3166-2:UG')
CountryCode.create(:country => 'Ukraine', :code_2 => 'UA', :code_3 => 'UKR', :country_ja => 'ウクライナ', :area => '東ヨーロッパ', :code_type => 'ISO 3166-2:UA')
CountryCode.create(:country => 'United Arab Emirates', :code_2 => 'AE', :code_3 => 'ARE', :country_ja => 'アラブ首長国連邦', :area => '中東', :code_type => 'ISO 3166-2:AE')
CountryCode.create(:country => 'United Kingdom', :code_2 => 'GB', :code_3 => 'GBR', :country_ja => 'イギリス', :area => '西ヨーロッパ', :code_type => 'ISO 3166-2:GB')
CountryCode.create(:country => 'United States', :code_2 => 'US', :code_3 => 'USA', :country_ja => 'アメリカ合衆国', :area => '北アメリカ', :code_type => 'ISO 3166-2:US')
CountryCode.create(:country => 'United States Minor Outlying Islands', :code_2 => 'UM', :code_3 => 'UMI', :country_ja => '合衆国領有小離島', :area => 'オセアニア', :code_type => 'ISO 3166-2:UM')
CountryCode.create(:country => 'Uruguay', :code_2 => 'UY', :code_3 => 'URY', :country_ja => 'ウルグアイ', :area => '南アメリカ', :code_type => 'ISO 3166-2:UY')
CountryCode.create(:country => 'Uzbekistan', :code_2 => 'UZ', :code_3 => 'UZB', :country_ja => 'ウズベキスタン', :area => '中央アジア', :code_type => 'ISO 3166-2:UZ')
CountryCode.create(:country => 'Vanuatu', :code_2 => 'VU', :code_3 => 'VUT', :country_ja => 'バヌアツ', :area => 'オセアニア', :code_type => 'ISO 3166-2:VU')
CountryCode.create(:country => 'Venezuela, Bolivarian Republic of', :code_2 => 'VE', :code_3 => 'VEN', :country_ja => 'ベネズエラ・ボリバル共和国', :area => '南アメリカ', :code_type => 'ISO 3166-2:VE')
CountryCode.create(:country => 'Viet Nam', :code_2 => 'VN', :code_3 => 'VNM', :country_ja => 'ベトナム', :area => '東南アジア', :code_type => 'ISO 3166-2:VN')
CountryCode.create(:country => 'Virgin Islands, British', :code_2 => 'VG', :code_3 => 'VGB', :country_ja => 'イギリス領ヴァージン諸島', :area => '中央アメリカ', :code_type => 'ISO 3166-2:VG')
CountryCode.create(:country => 'Virgin Islands, U.S.', :code_2 => 'VI', :code_3 => 'VIR', :country_ja => 'アメリカ領ヴァージン諸島', :area => '中央アメリカ', :code_type => 'ISO 3166-2:VI')
CountryCode.create(:country => 'Wallis and Futuna', :code_2 => 'WF', :code_3 => 'WLF', :country_ja => 'ウォリス・フツナ', :area => 'オセアニア', :code_type => 'ISO 3166-2:WF')
CountryCode.create(:country => 'Western Sahara', :code_2 => 'EH', :code_3 => 'ESH', :country_ja => '西サハラ', :area => '西アフリカ', :code_type => 'ISO 3166-2:EH')
CountryCode.create(:country => 'Yemen', :code_2 => 'YE', :code_3 => 'YEM', :country_ja => 'イエメン', :area => '中東', :code_type => 'ISO 3166-2:YE')
CountryCode.create(:country => 'Zambia', :code_2 => 'ZM', :code_3 => 'ZMB', :country_ja => 'ザンビア', :area => '南アフリカ', :code_type => 'ISO 3166-2:ZM')
CountryCode.create(:country => 'Zimbabwe', :code_2 => 'ZW', :code_3 => 'ZWE', :country_ja => 'ジンバブエ', :area => '南アフリカ', :code_type => 'ISO 3166-2:ZW')
