# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Registry.create(:registry => 'ARIN', :regional_internet_registry => 'American Registry for Internet Numbers', :cover_area => '北アメリカ', :uri => 'https://www.arin.net/', :data_uri => 'ftp://ftp.arin.net/pub/stats/arin/', :data_file => 'delegated-arin-latest')
Registry.create(:registry => 'RIPE NCC', :regional_internet_registry => 'RIPE Network Coordination Centre', :cover_area => 'ヨーロッパ,中東,中央アジア', :uri => 'http://www.ripe.net/', :data_uri => 'ftp://ftp.ripe.net/pub/stats/ripencc/', :data_file => 'delegated-ripencc-extended-latest')
Registry.create(:registry => 'APNIC', :regional_internet_registry => 'Asia-Pacific Network Information Centre', :cover_area => 'アジア,太平洋地域', :uri => 'http://www.apnic.net/', :data_uri => 'ftp://ftp.apnic.net/apnic/stats/apnic/', :data_file => 'delegated-apnic-extended-latest')
Registry.create(:registry => 'LACNIC', :regional_internet_registry => 'Latin American and Caribbean Internet Address Registry', :cover_area => 'ラテンアメリカ,カリブ海地域', :uri => 'http://www.lacnic.net/es/web/lacnic/inicio', :data_uri => 'ftp://ftp.lacnic.net/pub/stats/lacnic/', :data_file => 'delegated-lacnic-extended-latest')
Registry.create(:registry => 'AfriNIC', :regional_internet_registry => 'African Network Information Centre', :cover_area => 'アフリカ', :uri => 'http://www.afrinic.net/', :data_uri => 'ftp://ftp.afrinic.net/pub/stats/afrinic/', :data_file => 'delegated-afrinic-extended-latest')

Country.create(:numeric => '020', :alpha3 => 'AND', :alpha2 => 'AD', :country_name => 'Andorra', :country_name_ja => 'アンドラ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:AD')
Country.create(:numeric => '784', :alpha3 => 'ARE', :alpha2 => 'AE', :country_name => 'United Arab Emirates', :country_name_ja => 'アラブ首長国連邦', :area => '中東', :administrative_division => 'ISO 3166-2:AE')
Country.create(:numeric => '004', :alpha3 => 'AFG', :alpha2 => 'AF', :country_name => 'Afghanistan', :country_name_ja => 'アフガニスタン', :area => '中東', :administrative_division => 'ISO 3166-2:AF')
Country.create(:numeric => '028', :alpha3 => 'ATG', :alpha2 => 'AG', :country_name => 'Antigua and Barbuda', :country_name_ja => 'アンティグア・バーブーダ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:AG')
Country.create(:numeric => '660', :alpha3 => 'AIA', :alpha2 => 'AI', :country_name => 'Anguilla', :country_name_ja => 'アンギラ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:AI')
Country.create(:numeric => '008', :alpha3 => 'ALB', :alpha2 => 'AL', :country_name => 'Albania', :country_name_ja => 'アルバニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:AL')
Country.create(:numeric => '051', :alpha3 => 'ARM', :alpha2 => 'AM', :country_name => 'Armenia', :country_name_ja => 'アルメニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:AM')
Country.create(:numeric => '024', :alpha3 => 'AGO', :alpha2 => 'AO', :country_name => 'Angola', :country_name_ja => 'アンゴラ', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:AO')
Country.create(:numeric => '010', :alpha3 => 'ATA', :alpha2 => 'AQ', :country_name => 'Antarctica', :country_name_ja => '南極', :area => '南極', :administrative_division => 'ISO 3166-2:AQ')
Country.create(:numeric => '032', :alpha3 => 'ARG', :alpha2 => 'AR', :country_name => 'Argentina', :country_name_ja => 'アルゼンチン', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:AR')
Country.create(:numeric => '016', :alpha3 => 'ASM', :alpha2 => 'AS', :country_name => 'American Samoa', :country_name_ja => 'アメリカ領サモア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:AS')
Country.create(:numeric => '040', :alpha3 => 'AUT', :alpha2 => 'AT', :country_name => 'Austria', :country_name_ja => 'オーストリア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:AT')
Country.create(:numeric => '036', :alpha3 => 'AUS', :alpha2 => 'AU', :country_name => 'Australia', :country_name_ja => 'オーストラリア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:AU')
Country.create(:numeric => '533', :alpha3 => 'ABW', :alpha2 => 'AW', :country_name => 'Aruba', :country_name_ja => 'アルバ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:AW')
Country.create(:numeric => '248', :alpha3 => 'ALA', :alpha2 => 'AX', :country_name => 'Åland Islands', :country_name_ja => 'オーランド諸島', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:AX')
Country.create(:numeric => '031', :alpha3 => 'AZE', :alpha2 => 'AZ', :country_name => 'Azerbaijan', :country_name_ja => 'アゼルバイジャン', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:AZ')
Country.create(:numeric => '070', :alpha3 => 'BIH', :alpha2 => 'BA', :country_name => 'Bosnia and Herzegovina', :country_name_ja => 'ボスニア・ヘルツェゴビナ', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:BA')
Country.create(:numeric => '052', :alpha3 => 'BRB', :alpha2 => 'BB', :country_name => 'Barbados', :country_name_ja => 'バルバドス', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BB')
Country.create(:numeric => '050', :alpha3 => 'BGD', :alpha2 => 'BD', :country_name => 'Bangladesh', :country_name_ja => 'バングラデシュ', :area => '南アジア', :administrative_division => 'ISO 3166-2:BD')
Country.create(:numeric => '056', :alpha3 => 'BEL', :alpha2 => 'BE', :country_name => 'Belgium', :country_name_ja => 'ベルギー', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:BE')
Country.create(:numeric => '854', :alpha3 => 'BFA', :alpha2 => 'BF', :country_name => 'Burkina Faso', :country_name_ja => 'ブルキナファソ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:BF')
Country.create(:numeric => '100', :alpha3 => 'BGR', :alpha2 => 'BG', :country_name => 'Bulgaria', :country_name_ja => 'ブルガリア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:BG')
Country.create(:numeric => '048', :alpha3 => 'BHR', :alpha2 => 'BH', :country_name => 'Bahrain', :country_name_ja => 'バーレーン', :area => '中東', :administrative_division => 'ISO 3166-2:BH')
Country.create(:numeric => '108', :alpha3 => 'BDI', :alpha2 => 'BI', :country_name => 'Burundi', :country_name_ja => 'ブルンジ', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:BI')
Country.create(:numeric => '204', :alpha3 => 'BEN', :alpha2 => 'BJ', :country_name => 'Benin', :country_name_ja => 'ベナン', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:BJ')
Country.create(:numeric => '652', :alpha3 => 'BLM', :alpha2 => 'BL', :country_name => 'Saint Barthélemy', :country_name_ja => 'サン・バルテルミー', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BL')
Country.create(:numeric => '060', :alpha3 => 'BMU', :alpha2 => 'BM', :country_name => 'Bermuda', :country_name_ja => 'バミューダ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BM')
Country.create(:numeric => '096', :alpha3 => 'BRN', :alpha2 => 'BN', :country_name => 'Brunei Darussalam', :country_name_ja => 'ブルネイ・ダルサラーム', :area => '東南アジア', :administrative_division => 'ISO 3166-2:BN')
Country.create(:numeric => '068', :alpha3 => 'BOL', :alpha2 => 'BO', :country_name => 'Bolivia, Plurinational State of', :country_name_ja => 'ボリビア多民族国', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:BO')
Country.create(:numeric => '535', :alpha3 => 'BES', :alpha2 => 'BQ', :country_name => 'Bonaire, Saint Eustatius and Saba', :country_name_ja => 'ボネール、シント・ユースタティウスおよびサバ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BQ')
Country.create(:numeric => '076', :alpha3 => 'BRA', :alpha2 => 'BR', :country_name => 'Brazil', :country_name_ja => 'ブラジル', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:BR')
Country.create(:numeric => '044', :alpha3 => 'BHS', :alpha2 => 'BS', :country_name => 'Bahamas', :country_name_ja => 'バハマ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BS')
Country.create(:numeric => '064', :alpha3 => 'BTN', :alpha2 => 'BT', :country_name => 'Bhutan', :country_name_ja => 'ブータン', :area => '南アジア', :administrative_division => 'ISO 3166-2:BT')
Country.create(:numeric => '074', :alpha3 => 'BVT', :alpha2 => 'BV', :country_name => 'Bouvet Island', :country_name_ja => 'ブーベ島', :area => '南極', :administrative_division => 'ISO 3166-2:BV')
Country.create(:numeric => '072', :alpha3 => 'BWA', :alpha2 => 'BW', :country_name => 'Botswana', :country_name_ja => 'ボツワナ', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:BW')
Country.create(:numeric => '112', :alpha3 => 'BLR', :alpha2 => 'BY', :country_name => 'Belarus', :country_name_ja => 'ベラルーシ', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:BY')
Country.create(:numeric => '084', :alpha3 => 'BLZ', :alpha2 => 'BZ', :country_name => 'Belize', :country_name_ja => 'ベリーズ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:BZ')
Country.create(:numeric => '124', :alpha3 => 'CAN', :alpha2 => 'CA', :country_name => 'Canada', :country_name_ja => 'カナダ', :area => '北アメリカ', :administrative_division => 'ISO 3166-2:CA')
Country.create(:numeric => '166', :alpha3 => 'CCK', :alpha2 => 'CC', :country_name => 'Cocos (Keeling) Islands', :country_name_ja => 'ココス（キーリング）諸島', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:CC')
Country.create(:numeric => '180', :alpha3 => 'COD', :alpha2 => 'CD', :country_name => 'Congo, the Democratic Republic of the', :country_name_ja => 'コンゴ民主共和国', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:CD')
Country.create(:numeric => '140', :alpha3 => 'CAF', :alpha2 => 'CF', :country_name => 'Central African Republic', :country_name_ja => '中央アフリカ共和国', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:CF')
Country.create(:numeric => '178', :alpha3 => 'COG', :alpha2 => 'CG', :country_name => 'Congo', :country_name_ja => 'コンゴ共和国', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:CG')
Country.create(:numeric => '756', :alpha3 => 'CHE', :alpha2 => 'CH', :country_name => 'Switzerland', :country_name_ja => 'スイス', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:CH')
Country.create(:numeric => '384', :alpha3 => 'CIV', :alpha2 => 'CI', :country_name => 'Côte d\'Ivoire', :country_name_ja => 'コートジボワール', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:CI')
Country.create(:numeric => '184', :alpha3 => 'COK', :alpha2 => 'CK', :country_name => 'Cook Islands', :country_name_ja => 'クック諸島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:CK')
Country.create(:numeric => '152', :alpha3 => 'CHL', :alpha2 => 'CL', :country_name => 'Chile', :country_name_ja => 'チリ', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:CL')
Country.create(:numeric => '120', :alpha3 => 'CMR', :alpha2 => 'CM', :country_name => 'Cameroon', :country_name_ja => 'カメルーン', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:CM')
Country.create(:numeric => '156', :alpha3 => 'CHN', :alpha2 => 'CN', :country_name => 'China', :country_name_ja => '中国', :area => '東アジア', :administrative_division => 'ISO 3166-2:CN')
Country.create(:numeric => '170', :alpha3 => 'COL', :alpha2 => 'CO', :country_name => 'Colombia', :country_name_ja => 'コロンビア', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:CO')
Country.create(:numeric => '188', :alpha3 => 'CRI', :alpha2 => 'CR', :country_name => 'Costa Rica', :country_name_ja => 'コスタリカ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:CR')
Country.create(:numeric => '192', :alpha3 => 'CUB', :alpha2 => 'CU', :country_name => 'Cuba', :country_name_ja => 'キューバ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:CU')
Country.create(:numeric => '132', :alpha3 => 'CPV', :alpha2 => 'CV', :country_name => 'Cape Verde', :country_name_ja => 'カーボベルデ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:CV')
Country.create(:numeric => '531', :alpha3 => 'CUW', :alpha2 => 'CW', :country_name => 'Curaçao', :country_name_ja => 'キュラソー', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:CW')
Country.create(:numeric => '162', :alpha3 => 'CXR', :alpha2 => 'CX', :country_name => 'Christmas Island', :country_name_ja => 'クリスマス島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:CX')
Country.create(:numeric => '196', :alpha3 => 'CYP', :alpha2 => 'CY', :country_name => 'Cyprus', :country_name_ja => 'キプロス', :area => '地中海地域', :administrative_division => 'ISO 3166-2:CY')
Country.create(:numeric => '203', :alpha3 => 'CZE', :alpha2 => 'CZ', :country_name => 'Czech Republic', :country_name_ja => 'チェコ', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:CZ')
Country.create(:numeric => '276', :alpha3 => 'DEU', :alpha2 => 'DE', :country_name => 'Germany', :country_name_ja => 'ドイツ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:DE')
Country.create(:numeric => '262', :alpha3 => 'DJI', :alpha2 => 'DJ', :country_name => 'Djibouti', :country_name_ja => 'ジブチ', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:DJ')
Country.create(:numeric => '208', :alpha3 => 'DNK', :alpha2 => 'DK', :country_name => 'Denmark', :country_name_ja => 'デンマーク', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:DK')
Country.create(:numeric => '212', :alpha3 => 'DMA', :alpha2 => 'DM', :country_name => 'Dominica', :country_name_ja => 'ドミニカ国', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:DM')
Country.create(:numeric => '214', :alpha3 => 'DOM', :alpha2 => 'DO', :country_name => 'Dominican Republic', :country_name_ja => 'ドミニカ共和国', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:DO')
Country.create(:numeric => '012', :alpha3 => 'DZA', :alpha2 => 'DZ', :country_name => 'Algeria', :country_name_ja => 'アルジェリア', :area => '北アフリカ', :administrative_division => 'ISO 3166-2:DZ')
Country.create(:numeric => '218', :alpha3 => 'ECU', :alpha2 => 'EC', :country_name => 'Ecuador', :country_name_ja => 'エクアドル', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:EC')
Country.create(:numeric => '233', :alpha3 => 'EST', :alpha2 => 'EE', :country_name => 'Estonia', :country_name_ja => 'エストニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:EE')
Country.create(:numeric => '818', :alpha3 => 'EGY', :alpha2 => 'EG', :country_name => 'Egypt', :country_name_ja => 'エジプト', :area => '北アフリカ', :administrative_division => 'ISO 3166-2:EG')
Country.create(:numeric => '732', :alpha3 => 'ESH', :alpha2 => 'EH', :country_name => 'Western Sahara', :country_name_ja => '西サハラ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:EH')
Country.create(:numeric => '232', :alpha3 => 'ERI', :alpha2 => 'ER', :country_name => 'Eritrea', :country_name_ja => 'エリトリア', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:ER')
Country.create(:numeric => '724', :alpha3 => 'ESP', :alpha2 => 'ES', :country_name => 'Spain', :country_name_ja => 'スペイン', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:ES')
Country.create(:numeric => '231', :alpha3 => 'ETH', :alpha2 => 'ET', :country_name => 'Ethiopia', :country_name_ja => 'エチオピア', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:ET')
Country.create(:numeric => '246', :alpha3 => 'FIN', :alpha2 => 'FI', :country_name => 'Finland', :country_name_ja => 'フィンランド', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:FI')
Country.create(:numeric => '242', :alpha3 => 'FJI', :alpha2 => 'FJ', :country_name => 'Fiji', :country_name_ja => 'フィジー', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:FJ')
Country.create(:numeric => '238', :alpha3 => 'FLK', :alpha2 => 'FK', :country_name => 'Falkland Islands (Malvinas)', :country_name_ja => 'フォークランド（マルビナス）諸島', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:FK')
Country.create(:numeric => '583', :alpha3 => 'FSM', :alpha2 => 'FM', :country_name => 'Micronesia, Federated States of', :country_name_ja => 'ミクロネシア連邦', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:FM')
Country.create(:numeric => '234', :alpha3 => 'FRO', :alpha2 => 'FO', :country_name => 'Faroe Islands', :country_name_ja => 'フェロー諸島', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:FO')
Country.create(:numeric => '250', :alpha3 => 'FRA', :alpha2 => 'FR', :country_name => 'France', :country_name_ja => 'フランス', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:FR')
Country.create(:numeric => '266', :alpha3 => 'GAB', :alpha2 => 'GA', :country_name => 'Gabon', :country_name_ja => 'ガボン', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:GA')
Country.create(:numeric => '826', :alpha3 => 'GBR', :alpha2 => 'GB', :country_name => 'United Kingdom', :country_name_ja => 'イギリス', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:GB')
Country.create(:numeric => '308', :alpha3 => 'GRD', :alpha2 => 'GD', :country_name => 'Grenada', :country_name_ja => 'グレナダ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:GD')
Country.create(:numeric => '268', :alpha3 => 'GEO', :alpha2 => 'GE', :country_name => 'Georgia', :country_name_ja => 'グルジア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:GE')
Country.create(:numeric => '254', :alpha3 => 'GUF', :alpha2 => 'GF', :country_name => 'French Guiana', :country_name_ja => 'フランス領ギアナ', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:GF')
Country.create(:numeric => '831', :alpha3 => 'GGY', :alpha2 => 'GG', :country_name => 'Guernsey', :country_name_ja => 'ガーンジー', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:GG')
Country.create(:numeric => '288', :alpha3 => 'GHA', :alpha2 => 'GH', :country_name => 'Ghana', :country_name_ja => 'ガーナ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:GH')
Country.create(:numeric => '292', :alpha3 => 'GIB', :alpha2 => 'GI', :country_name => 'Gibraltar', :country_name_ja => 'ジブラルタル', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:GI')
Country.create(:numeric => '304', :alpha3 => 'GRL', :alpha2 => 'GL', :country_name => 'Greenland', :country_name_ja => 'グリーンランド', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:GL')
Country.create(:numeric => '270', :alpha3 => 'GMB', :alpha2 => 'GM', :country_name => 'Gambia', :country_name_ja => 'ガンビア', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:GM')
Country.create(:numeric => '324', :alpha3 => 'GIN', :alpha2 => 'GN', :country_name => 'Guinea', :country_name_ja => 'ギニア', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:GN')
Country.create(:numeric => '312', :alpha3 => 'GLP', :alpha2 => 'GP', :country_name => 'Guadeloupe', :country_name_ja => 'グアドループ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:GP')
Country.create(:numeric => '226', :alpha3 => 'GNQ', :alpha2 => 'GQ', :country_name => 'Equatorial Guinea', :country_name_ja => '赤道ギニア', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:GQ')
Country.create(:numeric => '300', :alpha3 => 'GRC', :alpha2 => 'GR', :country_name => 'Greece', :country_name_ja => 'ギリシャ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:GR')
Country.create(:numeric => '239', :alpha3 => 'SGS', :alpha2 => 'GS', :country_name => 'South Georgia and the South Sandwich Islands', :country_name_ja => 'サウスジョージア・サウスサンドウィッチ諸島', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:GS')
Country.create(:numeric => '320', :alpha3 => 'GTM', :alpha2 => 'GT', :country_name => 'Guatemala', :country_name_ja => 'グアテマラ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:GT')
Country.create(:numeric => '316', :alpha3 => 'GUM', :alpha2 => 'GU', :country_name => 'Guam', :country_name_ja => 'グアム', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:GU')
Country.create(:numeric => '624', :alpha3 => 'GNB', :alpha2 => 'GW', :country_name => 'Guinea-Bissau', :country_name_ja => 'ギニアビサウ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:GW')
Country.create(:numeric => '328', :alpha3 => 'GUY', :alpha2 => 'GY', :country_name => 'Guyana', :country_name_ja => 'ガイアナ', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:GY')
Country.create(:numeric => '344', :alpha3 => 'HKG', :alpha2 => 'HK', :country_name => 'Hong Kong', :country_name_ja => '香港', :area => '東アジア', :administrative_division => 'ISO 3166-2:HK')
Country.create(:numeric => '334', :alpha3 => 'HMD', :alpha2 => 'HM', :country_name => 'Heard Island and McDonald Islands', :country_name_ja => 'ハード島とマクドナルド諸島', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:HM')
Country.create(:numeric => '340', :alpha3 => 'HND', :alpha2 => 'HN', :country_name => 'Honduras', :country_name_ja => 'ホンジュラス', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:HN')
Country.create(:numeric => '191', :alpha3 => 'HRV', :alpha2 => 'HR', :country_name => 'Croatia', :country_name_ja => 'クロアチア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:HR')
Country.create(:numeric => '332', :alpha3 => 'HTI', :alpha2 => 'HT', :country_name => 'Haiti', :country_name_ja => 'ハイチ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:HT')
Country.create(:numeric => '348', :alpha3 => 'HUN', :alpha2 => 'HU', :country_name => 'Hungary', :country_name_ja => 'ハンガリー', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:HU')
Country.create(:numeric => '360', :alpha3 => 'IDN', :alpha2 => 'ID', :country_name => 'Indonesia', :country_name_ja => 'インドネシア', :area => '東南アジア', :administrative_division => 'ISO 3166-2:ID')
Country.create(:numeric => '372', :alpha3 => 'IRL', :alpha2 => 'IE', :country_name => 'Ireland', :country_name_ja => 'アイルランド', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:IE')
Country.create(:numeric => '376', :alpha3 => 'ISR', :alpha2 => 'IL', :country_name => 'Israel', :country_name_ja => 'イスラエル', :area => '中東', :administrative_division => 'ISO 3166-2:IL')
Country.create(:numeric => '833', :alpha3 => 'IMN', :alpha2 => 'IM', :country_name => 'Isle of Man', :country_name_ja => 'マン島', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:IM')
Country.create(:numeric => '356', :alpha3 => 'IND', :alpha2 => 'IN', :country_name => 'India', :country_name_ja => 'インド', :area => '南アジア', :administrative_division => 'ISO 3166-2:IN')
Country.create(:numeric => '086', :alpha3 => 'IOT', :alpha2 => 'IO', :country_name => 'British Indian Ocean Territory', :country_name_ja => 'イギリス領インド洋地域', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:IO')
Country.create(:numeric => '368', :alpha3 => 'IRQ', :alpha2 => 'IQ', :country_name => 'Iraq', :country_name_ja => 'イラク', :area => '中東', :administrative_division => 'ISO 3166-2:IQ')
Country.create(:numeric => '364', :alpha3 => 'IRN', :alpha2 => 'IR', :country_name => 'Iran, Islamic Republic of', :country_name_ja => 'イラン・イスラム共和国', :area => '中東', :administrative_division => 'ISO 3166-2:IR')
Country.create(:numeric => '352', :alpha3 => 'ISL', :alpha2 => 'IS', :country_name => 'Iceland', :country_name_ja => 'アイスランド', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:IS')
Country.create(:numeric => '380', :alpha3 => 'ITA', :alpha2 => 'IT', :country_name => 'Italy', :country_name_ja => 'イタリア', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:IT')
Country.create(:numeric => '832', :alpha3 => 'JEY', :alpha2 => 'JE', :country_name => 'Jersey', :country_name_ja => 'ジャージー', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:JE')
Country.create(:numeric => '388', :alpha3 => 'JAM', :alpha2 => 'JM', :country_name => 'Jamaica', :country_name_ja => 'ジャマイカ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:JM')
Country.create(:numeric => '400', :alpha3 => 'JOR', :alpha2 => 'JO', :country_name => 'Jordan', :country_name_ja => 'ヨルダン', :area => '中東', :administrative_division => 'ISO 3166-2:JO')
Country.create(:numeric => '392', :alpha3 => 'JPN', :alpha2 => 'JP', :country_name => 'Japan', :country_name_ja => '日本', :area => '東アジア', :administrative_division => 'ISO 3166-2:JP')
Country.create(:numeric => '404', :alpha3 => 'KEN', :alpha2 => 'KE', :country_name => 'Kenya', :country_name_ja => 'ケニア', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:KE')
Country.create(:numeric => '417', :alpha3 => 'KGZ', :alpha2 => 'KG', :country_name => 'Kyrgyzstan', :country_name_ja => 'キルギス', :area => '中央アジア', :administrative_division => 'ISO 3166-2:KG')
Country.create(:numeric => '116', :alpha3 => 'KHM', :alpha2 => 'KH', :country_name => 'Cambodia', :country_name_ja => 'カンボジア', :area => '東南アジア', :administrative_division => 'ISO 3166-2:KH')
Country.create(:numeric => '296', :alpha3 => 'KIR', :alpha2 => 'KI', :country_name => 'Kiribati', :country_name_ja => 'キリバス', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:KI')
Country.create(:numeric => '174', :alpha3 => 'COM', :alpha2 => 'KM', :country_name => 'Comoros', :country_name_ja => 'コモロ', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:KM')
Country.create(:numeric => '659', :alpha3 => 'KNA', :alpha2 => 'KN', :country_name => 'Saint Kitts and Nevis', :country_name_ja => 'セントクリストファー・ネイビス', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:KN')
Country.create(:numeric => '408', :alpha3 => 'PRK', :alpha2 => 'KP', :country_name => 'Korea, Democratic People\'s Republic of', :country_name_ja => '朝鮮民主主義人民共和国', :area => '東アジア', :administrative_division => 'ISO 3166-2:KP')
Country.create(:numeric => '410', :alpha3 => 'KOR', :alpha2 => 'KR', :country_name => 'Korea, Republic of', :country_name_ja => '大韓民国', :area => '東アジア', :administrative_division => 'ISO 3166-2:KR')
Country.create(:numeric => '414', :alpha3 => 'KWT', :alpha2 => 'KW', :country_name => 'Kuwait', :country_name_ja => 'クウェート', :area => '中東', :administrative_division => 'ISO 3166-2:KW')
Country.create(:numeric => '136', :alpha3 => 'CYM', :alpha2 => 'KY', :country_name => 'Cayman Islands', :country_name_ja => 'ケイマン諸島', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:KY')
Country.create(:numeric => '398', :alpha3 => 'KAZ', :alpha2 => 'KZ', :country_name => 'Kazakhstan', :country_name_ja => 'カザフスタン', :area => '中央アジア', :administrative_division => 'ISO 3166-2:KZ')
Country.create(:numeric => '418', :alpha3 => 'LAO', :alpha2 => 'LA', :country_name => 'Lao People\'s Democratic Republic', :country_name_ja => 'ラオス人民民主共和国', :area => '東南アジア', :administrative_division => 'ISO 3166-2:LA')
Country.create(:numeric => '422', :alpha3 => 'LBN', :alpha2 => 'LB', :country_name => 'Lebanon', :country_name_ja => 'レバノン', :area => '中東', :administrative_division => 'ISO 3166-2:LB')
Country.create(:numeric => '662', :alpha3 => 'LCA', :alpha2 => 'LC', :country_name => 'Saint Lucia', :country_name_ja => 'セントルシア', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:LC')
Country.create(:numeric => '438', :alpha3 => 'LIE', :alpha2 => 'LI', :country_name => 'Liechtenstein', :country_name_ja => 'リヒテンシュタイン', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:LI')
Country.create(:numeric => '144', :alpha3 => 'LKA', :alpha2 => 'LK', :country_name => 'Sri Lanka', :country_name_ja => 'スリランカ', :area => '南アジア', :administrative_division => 'ISO 3166-2:LK')
Country.create(:numeric => '430', :alpha3 => 'LBR', :alpha2 => 'LR', :country_name => 'Liberia', :country_name_ja => 'リベリア', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:LR')
Country.create(:numeric => '426', :alpha3 => 'LSO', :alpha2 => 'LS', :country_name => 'Lesotho', :country_name_ja => 'レソト', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:LS')
Country.create(:numeric => '440', :alpha3 => 'LTU', :alpha2 => 'LT', :country_name => 'Lithuania', :country_name_ja => 'リトアニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:LT')
Country.create(:numeric => '442', :alpha3 => 'LUX', :alpha2 => 'LU', :country_name => 'Luxembourg', :country_name_ja => 'ルクセンブルク', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:LU')
Country.create(:numeric => '428', :alpha3 => 'LVA', :alpha2 => 'LV', :country_name => 'Latvia', :country_name_ja => 'ラトビア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:LV')
Country.create(:numeric => '434', :alpha3 => 'LBY', :alpha2 => 'LY', :country_name => 'Libya', :country_name_ja => 'リビア', :area => '北アフリカ', :administrative_division => 'ISO 3166-2:LY')
Country.create(:numeric => '504', :alpha3 => 'MAR', :alpha2 => 'MA', :country_name => 'Morocco', :country_name_ja => 'モロッコ', :area => '北アフリカ', :administrative_division => 'ISO 3166-2:MA')
Country.create(:numeric => '492', :alpha3 => 'MCO', :alpha2 => 'MC', :country_name => 'Monaco', :country_name_ja => 'モナコ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:MC')
Country.create(:numeric => '498', :alpha3 => 'MDA', :alpha2 => 'MD', :country_name => 'Moldova, Republic of', :country_name_ja => 'モルドバ共和国', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:MD')
Country.create(:numeric => '499', :alpha3 => 'MNE', :alpha2 => 'ME', :country_name => 'Montenegro', :country_name_ja => 'モンテネグロ', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:ME')
Country.create(:numeric => '663', :alpha3 => 'MAF', :alpha2 => 'MF', :country_name => 'Saint Martin (French part)', :country_name_ja => 'サン・マルタン（フランス領）', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:MF')
Country.create(:numeric => '450', :alpha3 => 'MDG', :alpha2 => 'MG', :country_name => 'Madagascar', :country_name_ja => 'マダガスカル', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:MG')
Country.create(:numeric => '584', :alpha3 => 'MHL', :alpha2 => 'MH', :country_name => 'Marshall Islands', :country_name_ja => 'マーシャル諸島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:MH')
Country.create(:numeric => '807', :alpha3 => 'MKD', :alpha2 => 'MK', :country_name => 'Macedonia, the former Yugoslav Republic of', :country_name_ja => 'マケドニア旧ユーゴスラビア共和国', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:MK')
Country.create(:numeric => '466', :alpha3 => 'MLI', :alpha2 => 'ML', :country_name => 'Mali', :country_name_ja => 'マリ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:ML')
Country.create(:numeric => '104', :alpha3 => 'MMR', :alpha2 => 'MM', :country_name => 'Myanmar', :country_name_ja => 'ミャンマー', :area => '東南アジア', :administrative_division => 'ISO 3166-2:MM')
Country.create(:numeric => '496', :alpha3 => 'MNG', :alpha2 => 'MN', :country_name => 'Mongolia', :country_name_ja => 'モンゴル', :area => '東アジア', :administrative_division => 'ISO 3166-2:MN')
Country.create(:numeric => '446', :alpha3 => 'MAC', :alpha2 => 'MO', :country_name => 'Macao', :country_name_ja => 'マカオ', :area => '東アジア', :administrative_division => 'ISO 3166-2:MO')
Country.create(:numeric => '580', :alpha3 => 'MNP', :alpha2 => 'MP', :country_name => 'Northern Mariana Islands', :country_name_ja => '北マリアナ諸島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:MP')
Country.create(:numeric => '474', :alpha3 => 'MTQ', :alpha2 => 'MQ', :country_name => 'Martinique', :country_name_ja => 'マルティニーク', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:MQ')
Country.create(:numeric => '478', :alpha3 => 'MRT', :alpha2 => 'MR', :country_name => 'Mauritania', :country_name_ja => 'モーリタニア', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:MR')
Country.create(:numeric => '500', :alpha3 => 'MSR', :alpha2 => 'MS', :country_name => 'Montserrat', :country_name_ja => 'モントセラト', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:MS')
Country.create(:numeric => '470', :alpha3 => 'MLT', :alpha2 => 'MT', :country_name => 'Malta', :country_name_ja => 'マルタ', :area => '地中海地域', :administrative_division => 'ISO 3166-2:MT')
Country.create(:numeric => '480', :alpha3 => 'MUS', :alpha2 => 'MU', :country_name => 'Mauritius', :country_name_ja => 'モーリシャス', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:MU')
Country.create(:numeric => '462', :alpha3 => 'MDV', :alpha2 => 'MV', :country_name => 'Maldives', :country_name_ja => 'モルディブ', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:MV')
Country.create(:numeric => '454', :alpha3 => 'MWI', :alpha2 => 'MW', :country_name => 'Malawi', :country_name_ja => 'マラウイ', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:MW')
Country.create(:numeric => '484', :alpha3 => 'MEX', :alpha2 => 'MX', :country_name => 'Mexico', :country_name_ja => 'メキシコ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:MX')
Country.create(:numeric => '458', :alpha3 => 'MYS', :alpha2 => 'MY', :country_name => 'Malaysia', :country_name_ja => 'マレーシア', :area => '東南アジア', :administrative_division => 'ISO 3166-2:MY')
Country.create(:numeric => '508', :alpha3 => 'MOZ', :alpha2 => 'MZ', :country_name => 'Mozambique', :country_name_ja => 'モザンビーク', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:MZ')
Country.create(:numeric => '516', :alpha3 => 'NAM', :alpha2 => 'NA', :country_name => 'Namibia', :country_name_ja => 'ナミビア', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:NA')
Country.create(:numeric => '540', :alpha3 => 'NCL', :alpha2 => 'NC', :country_name => 'New Caledonia', :country_name_ja => 'ニューカレドニア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:NC')
Country.create(:numeric => '562', :alpha3 => 'NER', :alpha2 => 'NE', :country_name => 'Niger', :country_name_ja => 'ニジェール', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:NE')
Country.create(:numeric => '574', :alpha3 => 'NFK', :alpha2 => 'NF', :country_name => 'Norfolk Island', :country_name_ja => 'ノーフォーク島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:NF')
Country.create(:numeric => '566', :alpha3 => 'NGA', :alpha2 => 'NG', :country_name => 'Nigeria', :country_name_ja => 'ナイジェリア', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:NG')
Country.create(:numeric => '558', :alpha3 => 'NIC', :alpha2 => 'NI', :country_name => 'Nicaragua', :country_name_ja => 'ニカラグア', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:NI')
Country.create(:numeric => '528', :alpha3 => 'NLD', :alpha2 => 'NL', :country_name => 'Netherlands', :country_name_ja => 'オランダ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:NL')
Country.create(:numeric => '578', :alpha3 => 'NOR', :alpha2 => 'NO', :country_name => 'Norway', :country_name_ja => 'ノルウェー', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:NO')
Country.create(:numeric => '524', :alpha3 => 'NPL', :alpha2 => 'NP', :country_name => 'Nepal', :country_name_ja => 'ネパール', :area => '南アジア', :administrative_division => 'ISO 3166-2:NP')
Country.create(:numeric => '520', :alpha3 => 'NRU', :alpha2 => 'NR', :country_name => 'Nauru', :country_name_ja => 'ナウル', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:NR')
Country.create(:numeric => '570', :alpha3 => 'NIU', :alpha2 => 'NU', :country_name => 'Niue', :country_name_ja => 'ニウエ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:NU')
Country.create(:numeric => '554', :alpha3 => 'NZL', :alpha2 => 'NZ', :country_name => 'New Zealand', :country_name_ja => 'ニュージーランド', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:NZ')
Country.create(:numeric => '512', :alpha3 => 'OMN', :alpha2 => 'OM', :country_name => 'Oman', :country_name_ja => 'オマーン', :area => '中東', :administrative_division => 'ISO 3166-2:OM')
Country.create(:numeric => '591', :alpha3 => 'PAN', :alpha2 => 'PA', :country_name => 'Panama', :country_name_ja => 'パナマ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:PA')
Country.create(:numeric => '604', :alpha3 => 'PER', :alpha2 => 'PE', :country_name => 'Peru', :country_name_ja => 'ペルー', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:PE')
Country.create(:numeric => '258', :alpha3 => 'PYF', :alpha2 => 'PF', :country_name => 'French Polynesia', :country_name_ja => 'フランス領ポリネシア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:PF')
Country.create(:numeric => '598', :alpha3 => 'PNG', :alpha2 => 'PG', :country_name => 'Papua New Guinea', :country_name_ja => 'パプアニューギニア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:PG')
Country.create(:numeric => '608', :alpha3 => 'PHL', :alpha2 => 'PH', :country_name => 'Philippines', :country_name_ja => 'フィリピン', :area => '東南アジア', :administrative_division => 'ISO 3166-2:PH')
Country.create(:numeric => '586', :alpha3 => 'PAK', :alpha2 => 'PK', :country_name => 'Pakistan', :country_name_ja => 'パキスタン', :area => '南アジア', :administrative_division => 'ISO 3166-2:PK')
Country.create(:numeric => '616', :alpha3 => 'POL', :alpha2 => 'PL', :country_name => 'Poland', :country_name_ja => 'ポーランド', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:PL')
Country.create(:numeric => '666', :alpha3 => 'SPM', :alpha2 => 'PM', :country_name => 'Saint Pierre and Miquelon', :country_name_ja => 'サンピエール島・ミクロン島', :area => '北アメリカ', :administrative_division => 'ISO 3166-2:PM')
Country.create(:numeric => '612', :alpha3 => 'PCN', :alpha2 => 'PN', :country_name => 'Pitcairn', :country_name_ja => 'ピトケアン', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:PN')
Country.create(:numeric => '630', :alpha3 => 'PRI', :alpha2 => 'PR', :country_name => 'Puerto Rico', :country_name_ja => 'プエルトリコ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:PR')
Country.create(:numeric => '275', :alpha3 => 'PSE', :alpha2 => 'PS', :country_name => 'Palestinian Territory, Occupied', :country_name_ja => 'パレスチナ', :area => '中東', :administrative_division => 'ISO 3166-2:PS')
Country.create(:numeric => '620', :alpha3 => 'PRT', :alpha2 => 'PT', :country_name => 'Portugal', :country_name_ja => 'ポルトガル', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:PT')
Country.create(:numeric => '585', :alpha3 => 'PLW', :alpha2 => 'PW', :country_name => 'Palau', :country_name_ja => 'パラオ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:PW')
Country.create(:numeric => '600', :alpha3 => 'PRY', :alpha2 => 'PY', :country_name => 'Paraguay', :country_name_ja => 'パラグアイ', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:PY')
Country.create(:numeric => '634', :alpha3 => 'QAT', :alpha2 => 'QA', :country_name => 'Qatar', :country_name_ja => 'カタール', :area => '中東', :administrative_division => 'ISO 3166-2:QA')
Country.create(:numeric => '638', :alpha3 => 'REU', :alpha2 => 'RE', :country_name => 'Réunion', :country_name_ja => 'レユニオン', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:RE')
Country.create(:numeric => '642', :alpha3 => 'ROU', :alpha2 => 'RO', :country_name => 'Romania', :country_name_ja => 'ルーマニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:RO')
Country.create(:numeric => '688', :alpha3 => 'SRB', :alpha2 => 'RS', :country_name => 'Serbia', :country_name_ja => 'セルビア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:RS')
Country.create(:numeric => '643', :alpha3 => 'RUS', :alpha2 => 'RU', :country_name => 'Russian Federation', :country_name_ja => 'ロシア連邦', :area => 'ロシア', :administrative_division => 'ISO 3166-2:RU')
Country.create(:numeric => '646', :alpha3 => 'RWA', :alpha2 => 'RW', :country_name => 'Rwanda', :country_name_ja => 'ルワンダ', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:RW')
Country.create(:numeric => '682', :alpha3 => 'SAU', :alpha2 => 'SA', :country_name => 'Saudi Arabia', :country_name_ja => 'サウジアラビア', :area => '中東', :administrative_division => 'ISO 3166-2:SA')
Country.create(:numeric => '090', :alpha3 => 'SLB', :alpha2 => 'SB', :country_name => 'Solomon Islands', :country_name_ja => 'ソロモン諸島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:SB')
Country.create(:numeric => '690', :alpha3 => 'SYC', :alpha2 => 'SC', :country_name => 'Seychelles', :country_name_ja => 'セーシェル', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:SC')
Country.create(:numeric => '729', :alpha3 => 'SDN', :alpha2 => 'SD', :country_name => 'Sudan', :country_name_ja => 'スーダン', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:SD')
Country.create(:numeric => '752', :alpha3 => 'SWE', :alpha2 => 'SE', :country_name => 'Sweden', :country_name_ja => 'スウェーデン', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:SE')
Country.create(:numeric => '702', :alpha3 => 'SGP', :alpha2 => 'SG', :country_name => 'Singapore', :country_name_ja => 'シンガポール', :area => '東南アジア', :administrative_division => 'ISO 3166-2:SG')
Country.create(:numeric => '654', :alpha3 => 'SHN', :alpha2 => 'SH', :country_name => 'Saint Helena, Ascension and Tristan da Cunha', :country_name_ja => 'セントヘレナ・アセンションおよびトリスタンダクーニャ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:SH')
Country.create(:numeric => '705', :alpha3 => 'SVN', :alpha2 => 'SI', :country_name => 'Slovenia', :country_name_ja => 'スロベニア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:SI')
Country.create(:numeric => '744', :alpha3 => 'SJM', :alpha2 => 'SJ', :country_name => 'Svalbard and Jan Mayen', :country_name_ja => 'スヴァールバル諸島およびヤンマイエン島', :area => '北ヨーロッパ', :administrative_division => 'ISO 3166-2:SJ')
Country.create(:numeric => '703', :alpha3 => 'SVK', :alpha2 => 'SK', :country_name => 'Slovakia', :country_name_ja => 'スロバキア', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:SK')
Country.create(:numeric => '694', :alpha3 => 'SLE', :alpha2 => 'SL', :country_name => 'Sierra Leone', :country_name_ja => 'シエラレオネ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:SL')
Country.create(:numeric => '674', :alpha3 => 'SMR', :alpha2 => 'SM', :country_name => 'San Marino', :country_name_ja => 'サンマリノ', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:SM')
Country.create(:numeric => '686', :alpha3 => 'SEN', :alpha2 => 'SN', :country_name => 'Senegal', :country_name_ja => 'セネガル', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:SN')
Country.create(:numeric => '706', :alpha3 => 'SOM', :alpha2 => 'SO', :country_name => 'Somalia', :country_name_ja => 'ソマリア', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:SO')
Country.create(:numeric => '740', :alpha3 => 'SUR', :alpha2 => 'SR', :country_name => 'Suriname', :country_name_ja => 'スリナム', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:SR')
Country.create(:numeric => '728', :alpha3 => 'SSD', :alpha2 => 'SS', :country_name => 'South Sudan', :country_name_ja => '南スーダン', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:SS')
Country.create(:numeric => '678', :alpha3 => 'STP', :alpha2 => 'ST', :country_name => 'Sao Tome and Principe', :country_name_ja => 'サントメ・プリンシペ', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:ST')
Country.create(:numeric => '222', :alpha3 => 'SLV', :alpha2 => 'SV', :country_name => 'El Salvador', :country_name_ja => 'エルサルバドル', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:SV')
Country.create(:numeric => '534', :alpha3 => 'SXM', :alpha2 => 'SX', :country_name => 'Sint Maarten (Dutch part)', :country_name_ja => 'シント・マールテン（オランダ領）', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:SX')
Country.create(:numeric => '760', :alpha3 => 'SYR', :alpha2 => 'SY', :country_name => 'Syrian Arab Republic', :country_name_ja => 'シリア・アラブ共和国', :area => '中東', :administrative_division => 'ISO 3166-2:SY')
Country.create(:numeric => '748', :alpha3 => 'SWZ', :alpha2 => 'SZ', :country_name => 'Swaziland', :country_name_ja => 'スワジランド', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:SZ')
Country.create(:numeric => '796', :alpha3 => 'TCA', :alpha2 => 'TC', :country_name => 'Turks and Caicos Islands', :country_name_ja => 'タークス・カイコス諸島', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:TC')
Country.create(:numeric => '148', :alpha3 => 'TCD', :alpha2 => 'TD', :country_name => 'Chad', :country_name_ja => 'チャド', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:TD')
Country.create(:numeric => '260', :alpha3 => 'ATF', :alpha2 => 'TF', :country_name => 'French Southern Territories', :country_name_ja => 'フランス領南方・南極地域', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:TF')
Country.create(:numeric => '768', :alpha3 => 'TGO', :alpha2 => 'TG', :country_name => 'Togo', :country_name_ja => 'トーゴ', :area => '西アフリカ', :administrative_division => 'ISO 3166-2:TG')
Country.create(:numeric => '764', :alpha3 => 'THA', :alpha2 => 'TH', :country_name => 'Thailand', :country_name_ja => 'タイ', :area => '東南アジア', :administrative_division => 'ISO 3166-2:TH')
Country.create(:numeric => '762', :alpha3 => 'TJK', :alpha2 => 'TJ', :country_name => 'Tajikistan', :country_name_ja => 'タジキスタン', :area => '中央アジア', :administrative_division => 'ISO 3166-2:TJ')
Country.create(:numeric => '772', :alpha3 => 'TKL', :alpha2 => 'TK', :country_name => 'Tokelau', :country_name_ja => 'トケラウ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:TK')
Country.create(:numeric => '626', :alpha3 => 'TLS', :alpha2 => 'TL', :country_name => 'Timor-Leste', :country_name_ja => '東ティモール', :area => '東南アジア', :administrative_division => 'ISO 3166-2:TL')
Country.create(:numeric => '795', :alpha3 => 'TKM', :alpha2 => 'TM', :country_name => 'Turkmenistan', :country_name_ja => 'トルクメニスタン', :area => '中央アジア', :administrative_division => 'ISO 3166-2:TM')
Country.create(:numeric => '788', :alpha3 => 'TUN', :alpha2 => 'TN', :country_name => 'Tunisia', :country_name_ja => 'チュニジア', :area => '北アフリカ', :administrative_division => 'ISO 3166-2:TN')
Country.create(:numeric => '776', :alpha3 => 'TON', :alpha2 => 'TO', :country_name => 'Tonga', :country_name_ja => 'トンガ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:TO')
Country.create(:numeric => '792', :alpha3 => 'TUR', :alpha2 => 'TR', :country_name => 'Turkey', :country_name_ja => 'トルコ', :area => '中東', :administrative_division => 'ISO 3166-2:TR')
Country.create(:numeric => '780', :alpha3 => 'TTO', :alpha2 => 'TT', :country_name => 'Trinidad and Tobago', :country_name_ja => 'トリニダード・トバゴ', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:TT')
Country.create(:numeric => '798', :alpha3 => 'TUV', :alpha2 => 'TV', :country_name => 'Tuvalu', :country_name_ja => 'ツバル', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:TV')
Country.create(:numeric => '158', :alpha3 => 'TWN', :alpha2 => 'TW', :country_name => 'Taiwan, Province of China', :country_name_ja => '台湾（台湾省/中華民国）', :area => '東アジア', :administrative_division => 'ISO 3166-2:TW')
Country.create(:numeric => '834', :alpha3 => 'TZA', :alpha2 => 'TZ', :country_name => 'Tanzania, United Republic of', :country_name_ja => 'タンザニア', :area => '東アフリカ', :administrative_division => 'ISO 3166-2:TZ')
Country.create(:numeric => '804', :alpha3 => 'UKR', :alpha2 => 'UA', :country_name => 'Ukraine', :country_name_ja => 'ウクライナ', :area => '東ヨーロッパ', :administrative_division => 'ISO 3166-2:UA')
Country.create(:numeric => '800', :alpha3 => 'UGA', :alpha2 => 'UG', :country_name => 'Uganda', :country_name_ja => 'ウガンダ', :area => '中央アフリカ', :administrative_division => 'ISO 3166-2:UG')
Country.create(:numeric => '581', :alpha3 => 'UMI', :alpha2 => 'UM', :country_name => 'United States Minor Outlying Islands', :country_name_ja => '合衆国領有小離島', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:UM')
Country.create(:numeric => '840', :alpha3 => 'USA', :alpha2 => 'US', :country_name => 'United States', :country_name_ja => 'アメリカ合衆国', :area => '北アメリカ', :administrative_division => 'ISO 3166-2:US')
Country.create(:numeric => '858', :alpha3 => 'URY', :alpha2 => 'UY', :country_name => 'Uruguay', :country_name_ja => 'ウルグアイ', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:UY')
Country.create(:numeric => '860', :alpha3 => 'UZB', :alpha2 => 'UZ', :country_name => 'Uzbekistan', :country_name_ja => 'ウズベキスタン', :area => '中央アジア', :administrative_division => 'ISO 3166-2:UZ')
Country.create(:numeric => '336', :alpha3 => 'VAT', :alpha2 => 'VA', :country_name => 'Holy See (Vatican City State)', :country_name_ja => 'バチカン市国', :area => '西ヨーロッパ', :administrative_division => 'ISO 3166-2:VA')
Country.create(:numeric => '670', :alpha3 => 'VCT', :alpha2 => 'VC', :country_name => 'Saint Vincent and the Grenadines', :country_name_ja => 'セントビンセントおよびグレナディーン諸島', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:VC')
Country.create(:numeric => '862', :alpha3 => 'VEN', :alpha2 => 'VE', :country_name => 'Venezuela, Bolivarian Republic of', :country_name_ja => 'ベネズエラ・ボリバル共和国', :area => '南アメリカ', :administrative_division => 'ISO 3166-2:VE')
Country.create(:numeric => '092', :alpha3 => 'VGB', :alpha2 => 'VG', :country_name => 'Virgin Islands, British', :country_name_ja => 'イギリス領ヴァージン諸島', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:VG')
Country.create(:numeric => '850', :alpha3 => 'VIR', :alpha2 => 'VI', :country_name => 'Virgin Islands, U.S.', :country_name_ja => 'アメリカ領ヴァージン諸島', :area => '中央アメリカ', :administrative_division => 'ISO 3166-2:VI')
Country.create(:numeric => '704', :alpha3 => 'VNM', :alpha2 => 'VN', :country_name => 'Viet Nam', :country_name_ja => 'ベトナム', :area => '東南アジア', :administrative_division => 'ISO 3166-2:VN')
Country.create(:numeric => '548', :alpha3 => 'VUT', :alpha2 => 'VU', :country_name => 'Vanuatu', :country_name_ja => 'バヌアツ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:VU')
Country.create(:numeric => '876', :alpha3 => 'WLF', :alpha2 => 'WF', :country_name => 'Wallis and Futuna', :country_name_ja => 'ウォリス・フツナ', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:WF')
Country.create(:numeric => '882', :alpha3 => 'WSM', :alpha2 => 'WS', :country_name => 'Samoa', :country_name_ja => 'サモア', :area => 'オセアニア', :administrative_division => 'ISO 3166-2:WS')
Country.create(:numeric => '887', :alpha3 => 'YEM', :alpha2 => 'YE', :country_name => 'Yemen', :country_name_ja => 'イエメン', :area => '中東', :administrative_division => 'ISO 3166-2:YE')
Country.create(:numeric => '175', :alpha3 => 'MYT', :alpha2 => 'YT', :country_name => 'Mayotte', :country_name_ja => 'マヨット', :area => 'インド洋地域', :administrative_division => 'ISO 3166-2:YT')
Country.create(:numeric => '710', :alpha3 => 'ZAF', :alpha2 => 'ZA', :country_name => 'South Africa', :country_name_ja => '南アフリカ', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:ZA')
Country.create(:numeric => '894', :alpha3 => 'ZMB', :alpha2 => 'ZM', :country_name => 'Zambia', :country_name_ja => 'ザンビア', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:ZM')
Country.create(:numeric => '716', :alpha3 => 'ZWE', :alpha2 => 'ZW', :country_name => 'Zimbabwe', :country_name_ja => 'ジンバブエ', :area => '南アフリカ', :administrative_division => 'ISO 3166-2:ZW')
